services:
  # A Node.js web service
  - type: web
    name: nodejs-postgresql
    env: node
    repo: https://github.com/Brilliantwebdev1125/Estate-shopping-mall-api.git
    region: oregon
    branch: master
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: ~18.9.0
      - key: NODE_ENV
        value: production
